#!/bin/sh
curl -A '' -L -o CHARXSEC3XXXSoftwareBundleV190.raucb 'https://www.phoenixcontact.com/product/product/MTEzOTAxMg/downloads/11428257?_realm=be&_locale=en-BE&licenseTermsAccepted=true'
sha256sum -c CHARX-SEC-Software-Bundle-V190.raucb.sum
